import { Provider as ApiProvider } from "@/modules/api/Provider";
import { UIProvider } from "@/modules/ui/Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <UIProvider>
          <ApiProvider>{children}</ApiProvider>
        </UIProvider>
      </body>
    </html>
  );
}
