version: '3.8'

services:
  # web:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - backend
  #     - frontend

  backend:
    container_name: logetl_backend
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app:cached
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/logetl_development

  frontend:
    container_name: logetl_frontend
    build:
      context: './frontend'
      dockerfile: Dockerfile
    env_file:
      - frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:cached
    environment:
      - API_URL=http://localhost:4000/api

  db:
    image: postgres:14.0
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../../log:/root/log:cached
    environment:
      POSTGRES_DB: logetl_development
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

volumes:
  db_data:
